import type {
  Account,
  Activity,
  Contact,
  CrmUser,
  Opportunity,
  PaymentMirror,
  SendDocumentMirror,
  StageEvent,
} from "./types";
import { DEMO_NOW, ago, inDays, dateAgo } from "./seed-time";
import { buildSeedLeads, leadBookSnapshot } from "./seed-leads";

export { DEMO_NOW, ago, inDays, dateAgo };
export { leadBookSnapshot };

export const users: CrmUser[] = [
  {
    id: "usr_you",
    displayName: "You",
    email: "you@rivvetai.com",
    role: "ae",
    active: true,
  },
  {
    id: "usr_maya",
    displayName: "Maya Chen",
    email: "maya@rivvetai.com",
    role: "ae",
    active: true,
  },
  {
    id: "usr_jordan",
    displayName: "Jordan Lee",
    email: "jordan@rivvetai.com",
    role: "manager",
    active: true,
  },
  {
    id: "unassigned",
    displayName: "Unassigned",
    email: "",
    role: "ae",
    active: false,
  },
];

export const seedLeads = buildSeedLeads();

export const seedAccounts: Account[] = [
  {
    id: "A-220",
    name: "Summit Fleet",
    domain: "summitfleet.com",
    industry: "Fleet / logistics",
    status: "prospect",
    ownerId: "usr_you",
    arr: 0,
    billingEmail: null,
    nextAction: "Qualify budget",
    nextActionDue: inDays(2),
    lastTouch: ago(2),
    health: "watch",
    openOpps: 1,
    createdAt: ago(14),
    updatedAt: ago(2),
    employeeBand: "50-200",
    region: "Mountain",
    tags: ["fleet"],
  },
  {
    id: "A-214",
    name: "Northline HVAC",
    domain: "northlinehvac.com",
    industry: "Home services",
    status: "active",
    ownerId: "usr_you",
    arr: 54000,
    billingEmail: "ap@northlinehvac.com",
    nextAction: null,
    nextActionDue: null,
    lastTouch: ago(16),
    health: "risk",
    openOpps: 1,
    createdAt: ago(400),
    updatedAt: ago(16),
    employeeBand: "20-50",
    region: "Mountain",
    tags: ["hvac", "at-risk"],
  },
  {
    id: "A-208",
    name: "Brightpath Dental",
    domain: "brightpath.dental",
    industry: "Healthcare",
    status: "active",
    ownerId: "usr_you",
    arr: 72000,
    billingEmail: "billing@brightpath.dental",
    nextAction: "QBR prep",
    nextActionDue: inDays(5),
    lastTouch: ago(5),
    health: "healthy",
    openOpps: 1,
    createdAt: ago(320),
    updatedAt: ago(5),
    employeeBand: "100-250",
    region: "West",
    tags: ["healthcare"],
  },
  {
    id: "A-201",
    name: "Atlas Field Service",
    domain: "atlasfs.com",
    industry: "Field service",
    status: "active",
    ownerId: "usr_you",
    arr: 120000,
    billingEmail: "finance@atlasfs.com",
    nextAction: "Expansion intro",
    nextActionDue: inDays(3),
    lastTouch: ago(3),
    health: "healthy",
    openOpps: 1,
    createdAt: ago(500),
    updatedAt: ago(3),
    employeeBand: "250-500",
    region: "Northeast",
    tags: ["strategic"],
  },
  {
    id: "A-198",
    name: "Redwood Logistics",
    domain: "redwoodlog.com",
    industry: "Logistics",
    status: "at_risk",
    ownerId: "usr_maya",
    arr: 38000,
    billingEmail: "ap@redwoodlog.com",
    nextAction: "Save plan call",
    nextActionDue: inDays(-2),
    lastTouch: ago(18),
    health: "risk",
    openOpps: 1,
    createdAt: ago(280),
    updatedAt: ago(18),
    employeeBand: "50-200",
    region: "West",
    tags: ["churn-risk"],
  },
  {
    id: "A-190",
    name: "Harbor Clinics",
    domain: "harborclinics.org",
    industry: "Healthcare",
    status: "prospect",
    ownerId: "usr_jordan",
    arr: 0,
    billingEmail: null,
    nextAction: "Map stakeholders",
    nextActionDue: inDays(4),
    lastTouch: ago(1),
    health: "watch",
    openOpps: 1,
    createdAt: ago(20),
    updatedAt: ago(1),
    employeeBand: "200-500",
    region: "Pacific",
    tags: ["healthcare", "pilot"],
  },
];

export const seedContacts: Contact[] = [
  {
    id: "C-901",
    accountId: "A-220",
    leadId: "L-1042",
    firstName: "Priya",
    lastName: "Nair",
    title: "VP Ops",
    email: "priya@summitfleet.com",
    phone: "+1 303-555-0142",
    isPrimary: true,
    ownerId: "usr_you",
    createdAt: ago(2),
    updatedAt: ago(2),
  },
  {
    id: "C-902",
    accountId: "A-214",
    leadId: "L-1038",
    firstName: "Marcus",
    lastName: "Webb",
    title: "Owner",
    email: "marcus@northlinehvac.com",
    phone: "+1 720-555-0198",
    isPrimary: true,
    ownerId: "usr_you",
    createdAt: ago(12),
    updatedAt: ago(4),
  },
  {
    id: "C-903",
    accountId: "A-214",
    leadId: null,
    firstName: "Tina",
    lastName: "Webb",
    title: "Office Manager",
    email: "tina@northlinehvac.com",
    phone: null,
    isPrimary: false,
    ownerId: "usr_you",
    createdAt: ago(10),
    updatedAt: ago(10),
  },
  {
    id: "C-904",
    accountId: "A-208",
    leadId: "L-1031",
    firstName: "Elena",
    lastName: "Vos",
    title: "COO",
    email: "elena@brightpath.dental",
    phone: null,
    isPrimary: true,
    ownerId: "usr_you",
    createdAt: ago(18),
    updatedAt: ago(8),
  },
  {
    id: "C-905",
    accountId: "A-201",
    leadId: "L-1019",
    firstName: "Sam",
    lastName: "Okonkwo",
    title: "CEO",
    email: "sam@atlasfs.com",
    phone: "+1 646-555-0177",
    isPrimary: true,
    ownerId: "usr_you",
    createdAt: ago(200),
    updatedAt: ago(1),
  },
  {
    id: "C-906",
    accountId: "A-201",
    leadId: null,
    firstName: "Nora",
    lastName: "Kim",
    title: "VP RevOps",
    email: "nora@atlasfs.com",
    phone: "+1 646-555-0178",
    isPrimary: false,
    ownerId: "usr_you",
    createdAt: ago(90),
    updatedAt: ago(3),
  },
  {
    id: "C-907",
    accountId: "A-198",
    leadId: "L-1024",
    firstName: "Chris",
    lastName: "Alvarez",
    title: "Dir. Revenue",
    email: "chris@redwoodlog.com",
    phone: "+1 415-555-0110",
    isPrimary: true,
    ownerId: "usr_maya",
    createdAt: ago(45),
    updatedAt: ago(21),
  },
  {
    id: "C-908",
    accountId: "A-190",
    leadId: "L-1012",
    firstName: "Jules",
    lastName: "Park",
    title: "Procurement",
    email: "jules@harborclinics.org",
    phone: null,
    isPrimary: true,
    ownerId: "usr_jordan",
    createdAt: ago(0, 6),
    updatedAt: ago(0, 6),
  },
];

export const seedOpportunities: Opportunity[] = [
  {
    id: "O-881",
    gtmLeadId: "L-1042",
    name: "Summit Fleet — Dispatch AI",
    accountId: "A-220",
    accountName: "Summit Fleet",
    primaryContactId: "C-901",
    stage: "qualified",
    amount: 0,
    monthlyAmount: 0,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: inDays(22),
    nextAction: null,
    nextActionDue: null,
    lastTouch: ago(2),
    stageEnteredAt: dateAgo(9),
    probability: 20,
    forecastCategory: "pipeline",
    vertical: "fleet",
    region: "UT",
    notes: "",
    source: "inbound_demo",
    engagement: { opened: 2, replied: 1, calls: 0 },
    deal: {
      tab: "rivvet_ai",
      productId: null,
      termMonths: 12,
      freeMonths: 0,
      payment: "Monthly · Auto-pay",
      startDate: inDays(14),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    createdAt: ago(9),
    updatedAt: ago(2),
    sourceLeadId: "L-1042",
    packageSku: null,
    tags: ["new-logo"],
    scorePriority: 40,
  },
  {
    id: "O-874",
    gtmLeadId: "L-1038",
    name: "Northline HVAC — Rivvet AI",
    accountId: "A-214",
    accountName: "Northline HVAC",
    primaryContactId: "C-902",
    stage: "proposal_out",
    amount: 48500,
    monthlyAmount: 4000,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: inDays(9),
    nextAction: "Send revised proposal",
    nextActionDue: inDays(-1),
    lastTouch: ago(6),
    stageEnteredAt: dateAgo(16),
    probability: 80,
    forecastCategory: "best_case",
    vertical: "hvac",
    region: "CO",
    notes: "Need updated seat count + annual prepay line.",
    source: "partner",
    engagement: { opened: 4, replied: 2, calls: 3 },
    deal: {
      tab: "rivvet_ai",
      productId: "unlimited",
      termMonths: 12,
      freeMonths: 0,
      payment: "Monthly · Auto-pay",
      startDate: inDays(14),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    lockedSendState: "draft",
    lockedPaymentState: "none",
    pandadocDocumentId: "pd_doc_mirror_874",
    stripeCheckoutId: null,
    packageSku: "rivvet_ai_unlimited",
    createdAt: ago(40),
    updatedAt: ago(6),
    sourceLeadId: "L-1038",
    tags: ["renewal-path"],
    scorePriority: 72,
  },
  {
    id: "O-865",
    gtmLeadId: "L-1031",
    name: "Brightpath — Front desk AI",
    accountId: "A-208",
    accountName: "Brightpath Dental",
    primaryContactId: "C-904",
    stage: "demo_held",
    amount: 6500,
    monthlyAmount: 500,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: inDays(14),
    nextAction: "Legal redlines",
    nextActionDue: inDays(2),
    lastTouch: ago(3),
    stageEnteredAt: dateAgo(5),
    probability: 60,
    forecastCategory: "commit",
    vertical: "dental",
    region: "CA",
    notes: "Legal in loop on MSA.",
    source: "outbound",
    engagement: { opened: 6, replied: 3, calls: 2 },
    deal: {
      tab: "rivvet_ai",
      productId: "value_based",
      termMonths: 12,
      freeMonths: 1,
      payment: "Monthly · Auto-pay",
      startDate: inDays(21),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    lockedSendState: "sent",
    lockedPaymentState: "pending",
    pandadocDocumentId: "pd_doc_mirror_865",
    stripeCheckoutId: "cs_mirror_865",
    packageSku: "rivvet_ai_value_based",
    createdAt: ago(60),
    updatedAt: ago(3),
    sourceLeadId: "L-1031",
    tags: ["upsell"],
    scorePriority: 81,
  },
  {
    id: "O-852",
    gtmLeadId: "L-1019",
    name: "Atlas — Multi-location expand",
    accountId: "A-201",
    accountName: "Atlas Field Service",
    primaryContactId: "C-905",
    stage: "demo_booked",
    amount: 48500,
    monthlyAmount: 4000,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: inDays(6),
    nextAction: "Countersign package",
    nextActionDue: inDays(1),
    lastTouch: ago(1),
    stageEnteredAt: dateAgo(3),
    probability: 40,
    forecastCategory: "commit",
    vertical: "field_service",
    region: "NY",
    notes: "CEO verbal commit. Multi-location by month-end.",
    source: "referral",
    engagement: { opened: 8, replied: 5, calls: 4 },
    deal: {
      tab: "rivvet_ai",
      productId: "unlimited",
      termMonths: 12,
      freeMonths: 0,
      payment: "Annual · Paid upfront",
      startDate: inDays(10),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    lockedSendState: "viewed",
    lockedPaymentState: "pending",
    pandadocDocumentId: "pd_doc_mirror_852",
    stripeCheckoutId: "cs_mirror_852",
    packageSku: "rivvet_ai_unlimited",
    createdAt: ago(30),
    updatedAt: ago(1),
    sourceLeadId: "L-1019",
    tags: ["expansion", "strategic"],
    scorePriority: 94,
  },
  {
    id: "O-840",
    gtmLeadId: "L-1012",
    name: "Harbor Clinics — Pilot",
    accountId: "A-190",
    accountName: "Harbor Clinics",
    primaryContactId: "C-908",
    stage: "qualified",
    amount: 0,
    monthlyAmount: 0,
    currency: "USD",
    ownerId: "usr_jordan",
    closeDate: inDays(45),
    nextAction: "Security questionnaire",
    nextActionDue: inDays(7),
    lastTouch: ago(4),
    stageEnteredAt: dateAgo(8),
    probability: 20,
    forecastCategory: "pipeline",
    vertical: "dental",
    region: "WA",
    notes: "",
    source: "inbound",
    engagement: { opened: 1, replied: 1, calls: 0 },
    deal: {
      tab: "rivvet_ai",
      productId: null,
      termMonths: 12,
      freeMonths: 0,
      payment: "Monthly · Auto-pay",
      startDate: inDays(60),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    createdAt: ago(12),
    updatedAt: ago(4),
    sourceLeadId: "L-1012",
    packageSku: null,
    tags: ["pilot"],
    scorePriority: 55,
  },
  {
    id: "O-821",
    gtmLeadId: "L-1024",
    name: "Redwood — Retention save",
    accountId: "A-198",
    accountName: "Redwood Logistics",
    primaryContactId: "C-907",
    stage: "qualified",
    amount: 0,
    monthlyAmount: 0,
    currency: "USD",
    ownerId: "usr_maya",
    closeDate: inDays(-3),
    nextAction: "Executive sponsor call",
    nextActionDue: inDays(-3),
    lastTouch: ago(12),
    stageEnteredAt: dateAgo(20),
    probability: 20,
    forecastCategory: "omitted",
    vertical: "logistics",
    region: "CA",
    notes: "Churn risk save.",
    source: "cs_save",
    engagement: { opened: null, replied: 0, calls: 1 },
    deal: {
      tab: "rivvet_ai",
      productId: null,
      termMonths: 12,
      freeMonths: 0,
      payment: "Monthly · Auto-pay",
      startDate: inDays(7),
      setupFee: 0,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    createdAt: ago(25),
    updatedAt: ago(12),
    sourceLeadId: "L-1024",
    packageSku: null,
    tags: ["save"],
    scorePriority: 30,
  },
  {
    id: "O-799",
    gtmLeadId: null,
    name: "Atlas — Year-1 baseline",
    accountId: "A-201",
    accountName: "Atlas Field Service",
    primaryContactId: "C-905",
    stage: "closed_won",
    amount: 120000,
    monthlyAmount: 4000,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: dateAgo(90),
    nextAction: null,
    nextActionDue: null,
    lastTouch: ago(40),
    stageEnteredAt: dateAgo(90),
    probability: 100,
    forecastCategory: "closed",
    vertical: "field_service",
    region: "NY",
    notes: "Baseline enterprise win.",
    source: "expansion",
    engagement: { opened: 12, replied: 8, calls: 6 },
    deal: {
      tab: "rivvet_ai",
      productId: "unlimited",
      termMonths: 24,
      freeMonths: 0,
      payment: "Annual · Paid upfront",
      startDate: dateAgo(90),
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: inDays(0),
      launchDateTarget: inDays(14),
    },
    lockedSendState: "signed",
    lockedPaymentState: "paid",
    pandadocDocumentId: "pd_doc_mirror_799",
    stripeCheckoutId: "cs_mirror_799",
    packageSku: "rivvet_ai_unlimited",
    createdAt: ago(200),
    updatedAt: ago(90),
    sourceLeadId: null,
    tags: ["closed"],
    scorePriority: 100,
  },
  {
    id: "O-910",
    gtmLeadId: null,
    name: "Cornerstone Remodeling",
    accountId: "A-214",
    accountName: "Cornerstone Remodeling",
    primaryContactId: "C-902",
    stage: "qualified",
    amount: 0,
    monthlyAmount: 0,
    currency: "USD",
    ownerId: "usr_you",
    closeDate: "",
    nextAction: null,
    nextActionDue: null,
    lastTouch: ago(7),
    stageEnteredAt: dateAgo(7),
    probability: 50,
    forecastCategory: "commit",
    vertical: "hvac",
    region: "UT",
    notes: "",
    source: "manual_opportunity",
    engagement: { opened: null, replied: 1, calls: 1 },
    deal: {
      tab: "rivvet_ai",
      productId: null,
      termMonths: 12,
      freeMonths: 0,
      payment: "Monthly · Auto-pay",
      startDate: "2026-08-08",
      setupFee: 500,
      monthlyDiscount: 0,
      commerceSetupFee: 1000,
      commerceMonthlyRetainer: 250,
      performanceOption: "",
      customPerfRate: 10,
      customPerfTermMonths: 6,
      effectiveDate: "2026-08-08",
      launchDateTarget: "2026-08-22",
    },
    createdAt: ago(7),
    updatedAt: ago(7),
    sourceLeadId: null,
    packageSku: null,
    tags: ["manual"],
    scorePriority: 100,
  },
];

export const seedStageEvents: StageEvent[] = [
  {
    id: "SE-1",
    opportunityId: "O-874",
    fromStage: "qualified",
    toStage: "proposal_out",
    at: ago(16),
    byUserId: "usr_you",
    note: "Scope locked; moved to proposal",
  },
  {
    id: "SE-2",
    opportunityId: "O-874",
    fromStage: "qualified",
    toStage: "qualified",
    at: ago(28),
    byUserId: "usr_you",
    note: null,
  },
  {
    id: "SE-3",
    opportunityId: "O-865",
    fromStage: "proposal_out",
    toStage: "demo_held",
    at: ago(5),
    byUserId: "usr_you",
    note: "PandaDoc sent; legal in loop",
  },
  {
    id: "SE-4",
    opportunityId: "O-852",
    fromStage: "demo_held",
    toStage: "proposal_out",
    at: ago(3),
    byUserId: "usr_you",
    note: "Verbal commit from CEO",
  },
  {
    id: "SE-5",
    opportunityId: "O-881",
    fromStage: null,
    toStage: "qualified",
    at: ago(9),
    byUserId: "usr_you",
    note: "Created from lead L-1042",
  },
];

export const seedActivities: Activity[] = [
  {
    id: "T-501",
    type: "call",
    subject: "Discovery follow-up — Priya Nair",
    body: "Left voicemail; interested in dispatch AI pilot Q3.",
    relatedType: "lead",
    relatedId: "L-1042",
    relatedName: "Priya Nair",
    ownerId: "usr_you",
    dueAt: inDays(0),
    completedAt: null,
    createdAt: ago(0, 2),
    secondaryRelatedType: "opportunity",
    secondaryRelatedId: "O-881",
  },
  {
    id: "T-498",
    type: "email",
    subject: "Send revised proposal — Northline",
    body: "Need updated seat count + annual prepay line.",
    relatedType: "opportunity",
    relatedId: "O-874",
    relatedName: "Northline HVAC — Rivvet AI",
    ownerId: "usr_you",
    dueAt: inDays(-1),
    completedAt: null,
    createdAt: ago(2),
    secondaryRelatedType: "account",
    secondaryRelatedId: "A-214",
  },
  {
    id: "T-490",
    type: "meeting",
    subject: "Legal redlines review — Brightpath",
    body: "30m with Brightpath counsel + Rivvet legal.",
    relatedType: "opportunity",
    relatedId: "O-865",
    relatedName: "Brightpath — Front desk AI",
    ownerId: "usr_you",
    dueAt: inDays(2),
    completedAt: null,
    createdAt: ago(1),
  },
  {
    id: "T-482",
    type: "task",
    subject: "QBR deck for Brightpath",
    body: "Pull usage + ROI slides from CRM export.",
    relatedType: "account",
    relatedId: "A-208",
    relatedName: "Brightpath Dental",
    ownerId: "usr_you",
    dueAt: inDays(5),
    completedAt: null,
    createdAt: ago(3),
  },
  {
    id: "T-475",
    type: "call",
    subject: "Save plan — Redwood Logistics",
    body: "Sponsor cancelled last call; rebook exec.",
    relatedType: "account",
    relatedId: "A-198",
    relatedName: "Redwood Logistics",
    ownerId: "usr_maya",
    dueAt: inDays(-2),
    completedAt: null,
    createdAt: ago(5),
  },
  {
    id: "T-470",
    type: "note",
    subject: "Atlas verbal commit notes",
    body: "CEO: want multi-location live by month-end. Nora owns RevOps side.",
    relatedType: "opportunity",
    relatedId: "O-852",
    relatedName: "Atlas — Multi-location expand",
    ownerId: "usr_you",
    dueAt: null,
    completedAt: ago(1),
    createdAt: ago(1),
  },
  {
    id: "T-460",
    type: "stage_change",
    subject: "Stage → Negotiation",
    body: "Auto from stage events (mirror).",
    relatedType: "opportunity",
    relatedId: "O-865",
    relatedName: "Brightpath — Front desk AI",
    ownerId: "usr_you",
    dueAt: null,
    completedAt: ago(5),
    createdAt: ago(5),
  },
  {
    id: "T-455",
    type: "system",
    subject: "PandaDoc document viewed",
    body: "Mirror event pd_doc_mirror_852 — no live webhook.",
    relatedType: "opportunity",
    relatedId: "O-852",
    relatedName: "Atlas — Multi-location expand",
    ownerId: "usr_you",
    dueAt: null,
    completedAt: ago(1, 3),
    createdAt: ago(1, 3),
  },
  {
    id: "T-450",
    type: "email",
    subject: "Inbound demo request — Peak Roofing",
    body: "New lead L-1048 from home-services demo.",
    relatedType: "lead",
    relatedId: "L-1048",
    relatedName: "Devon Blake",
    ownerId: "usr_you",
    dueAt: inDays(0),
    completedAt: null,
    createdAt: ago(0, 2),
  },
  {
    id: "T-440",
    type: "meeting",
    subject: "Security questionnaire walkthrough",
    body: "Harbor IT + Rivvet security.",
    relatedType: "opportunity",
    relatedId: "O-840",
    relatedName: "Harbor Clinics — Pilot",
    ownerId: "usr_jordan",
    dueAt: inDays(7),
    completedAt: null,
    createdAt: ago(4),
  },
];

/** Read-only mirrors of locked integrations — never mutate in UI mutations */
export const seedSendDocuments: SendDocumentMirror[] = [
  {
    id: "SD-874",
    opportunityId: "O-874",
    provider: "pandadoc",
    status: "draft",
    templateKey: "rivvet-msa-v3",
    recipientEmail: "marcus@northlinehvac.com",
    amount: 36000,
    createdAt: ago(10),
    sentAt: null,
    signedAt: null,
    externalId: "pd_doc_mirror_874",
  },
  {
    id: "SD-865",
    opportunityId: "O-865",
    provider: "pandadoc",
    status: "sent",
    templateKey: "rivvet-msa-v3",
    recipientEmail: "elena@brightpath.dental",
    amount: 28000,
    createdAt: ago(8),
    sentAt: ago(5),
    signedAt: null,
    externalId: "pd_doc_mirror_865",
  },
  {
    id: "SD-852",
    opportunityId: "O-852",
    provider: "pandadoc",
    status: "viewed",
    templateKey: "rivvet-enterprise-v2",
    recipientEmail: "sam@atlasfs.com",
    amount: 95000,
    createdAt: ago(6),
    sentAt: ago(4),
    signedAt: null,
    externalId: "pd_doc_mirror_852",
  },
  {
    id: "SD-799",
    opportunityId: "O-799",
    provider: "pandadoc",
    status: "signed",
    templateKey: "rivvet-enterprise-v2",
    recipientEmail: "sam@atlasfs.com",
    amount: 120000,
    createdAt: ago(120),
    sentAt: ago(100),
    signedAt: ago(90),
    externalId: "pd_doc_mirror_799",
  },
];

export const seedPayments: PaymentMirror[] = [
  {
    id: "PAY-865",
    opportunityId: "O-865",
    provider: "stripe",
    status: "pending",
    amount: 28000,
    externalId: "cs_mirror_865",
    createdAt: ago(5),
    paidAt: null,
  },
  {
    id: "PAY-852",
    opportunityId: "O-852",
    provider: "stripe",
    status: "pending",
    amount: 95000,
    externalId: "cs_mirror_852",
    createdAt: ago(4),
    paidAt: null,
  },
  {
    id: "PAY-799",
    opportunityId: "O-799",
    provider: "stripe",
    status: "paid",
    amount: 120000,
    externalId: "cs_mirror_799",
    createdAt: ago(95),
    paidAt: ago(90),
  },
];
