/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppSequencesRouteImport } from './routes/_app/sequences'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads/$leadId'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/_app/opportunities/index'
import { Route as AppOpportunitiesOppIdRouteImport } from './routes/_app/opportunities/$oppId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOpportunitiesOppIdIndexRouteImport } from './routes/_app/opportunities/$oppId.index'
import { Route as AppOpportunitiesOppIdDealBuilderRouteImport } from './routes/_app/opportunities/$oppId.deal-builder'
import { Route as AppOpportunitiesOppIdSendRouteImport } from './routes/_app/opportunities/$oppId.send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesRoute = AppSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesOppIdRoute = AppOpportunitiesOppIdRouteImport.update({
  id: '/opportunities/$oppId',
  path: '/opportunities/$oppId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOpportunitiesOppIdIndexRoute =
  AppOpportunitiesOppIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOpportunitiesOppIdRoute,
  } as any)
const AppOpportunitiesOppIdDealBuilderRoute =
  AppOpportunitiesOppIdDealBuilderRouteImport.update({
    id: '/deal-builder',
    path: '/deal-builder',
    getParentRoute: () => AppOpportunitiesOppIdRoute,
  } as any)
const AppOpportunitiesOppIdSendRoute =
  AppOpportunitiesOppIdSendRouteImport.update({
    id: '/send',
    path: '/send',
    getParentRoute: () => AppOpportunitiesOppIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/home': typeof AppHomeRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/opportunities/': typeof AppOpportunitiesIndexRoute
  '/opportunities/$oppId/deal-builder': typeof AppOpportunitiesOppIdDealBuilderRoute
  '/opportunities/$oppId/send': typeof AppOpportunitiesOppIdSendRoute
  '/opportunities/$oppId/': typeof AppOpportunitiesOppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/home': typeof AppHomeRoute
  '/sequences': typeof AppSequencesRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/opportunities': typeof AppOpportunitiesIndexRoute
  '/opportunities/$oppId/deal-builder': typeof AppOpportunitiesOppIdDealBuilderRoute
  '/opportunities/$oppId/send': typeof AppOpportunitiesOppIdSendRoute
  '/opportunities/$oppId': typeof AppOpportunitiesOppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/sequences': typeof AppSequencesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/opportunities/$oppId': typeof AppOpportunitiesOppIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/_app/opportunities/$oppId/deal-builder': typeof AppOpportunitiesOppIdDealBuilderRoute
  '/_app/opportunities/$oppId/send': typeof AppOpportunitiesOppIdSendRoute
  '/_app/opportunities/$oppId/': typeof AppOpportunitiesOppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/analytics'
    | '/home'
    | '/sequences'
    | '/settings'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/opportunities/$oppId'
    | '/api/auth/$'
    | '/accounts/'
    | '/leads/'
    | '/opportunities/'
    | '/opportunities/$oppId/deal-builder'
    | '/opportunities/$oppId/send'
    | '/opportunities/$oppId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/analytics'
    | '/home'
    | '/sequences'
    | '/settings'
    | '/accounts/$accountId'
    | '/leads/$leadId'
    | '/api/auth/$'
    | '/accounts'
    | '/leads'
    | '/opportunities'
    | '/opportunities/$oppId/deal-builder'
    | '/opportunities/$oppId/send'
    | '/opportunities/$oppId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activities'
    | '/_app/analytics'
    | '/_app/home'
    | '/_app/sequences'
    | '/_app/settings'
    | '/_app/accounts/$accountId'
    | '/_app/leads/$leadId'
    | '/_app/opportunities/$oppId'
    | '/api/auth/$'
    | '/_app/accounts/'
    | '/_app/leads/'
    | '/_app/opportunities/'
    | '/_app/opportunities/$oppId/deal-builder'
    | '/_app/opportunities/$oppId/send'
    | '/_app/opportunities/$oppId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequences': {
      id: '/_app/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AppSequencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/': {
      id: '/_app/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/$oppId': {
      id: '/_app/opportunities/$oppId'
      path: '/opportunities/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof AppOpportunitiesOppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/opportunities/$oppId/': {
      id: '/_app/opportunities/$oppId/'
      path: '/'
      fullPath: '/opportunities/$oppId/'
      preLoaderRoute: typeof AppOpportunitiesOppIdIndexRouteImport
      parentRoute: typeof AppOpportunitiesOppIdRoute
    }
    '/_app/opportunities/$oppId/deal-builder': {
      id: '/_app/opportunities/$oppId/deal-builder'
      path: '/deal-builder'
      fullPath: '/opportunities/$oppId/deal-builder'
      preLoaderRoute: typeof AppOpportunitiesOppIdDealBuilderRouteImport
      parentRoute: typeof AppOpportunitiesOppIdRoute
    }
    '/_app/opportunities/$oppId/send': {
      id: '/_app/opportunities/$oppId/send'
      path: '/send'
      fullPath: '/opportunities/$oppId/send'
      preLoaderRoute: typeof AppOpportunitiesOppIdSendRouteImport
      parentRoute: typeof AppOpportunitiesOppIdRoute
    }
  }
}

interface AppOpportunitiesOppIdRouteChildren {
  AppOpportunitiesOppIdDealBuilderRoute: typeof AppOpportunitiesOppIdDealBuilderRoute
  AppOpportunitiesOppIdSendRoute: typeof AppOpportunitiesOppIdSendRoute
  AppOpportunitiesOppIdIndexRoute: typeof AppOpportunitiesOppIdIndexRoute
}

const AppOpportunitiesOppIdRouteChildren: AppOpportunitiesOppIdRouteChildren = {
  AppOpportunitiesOppIdDealBuilderRoute: AppOpportunitiesOppIdDealBuilderRoute,
  AppOpportunitiesOppIdSendRoute: AppOpportunitiesOppIdSendRoute,
  AppOpportunitiesOppIdIndexRoute: AppOpportunitiesOppIdIndexRoute,
}

const AppOpportunitiesOppIdRouteWithChildren =
  AppOpportunitiesOppIdRoute._addFileChildren(
    AppOpportunitiesOppIdRouteChildren,
  )

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSequencesRoute: typeof AppSequencesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppOpportunitiesOppIdRoute: typeof AppOpportunitiesOppIdRouteWithChildren
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHomeRoute: AppHomeRoute,
  AppSequencesRoute: AppSequencesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppOpportunitiesOppIdRoute: AppOpportunitiesOppIdRouteWithChildren,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
